/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cayden_process_Watcher */

#ifndef _Included_com_cayden_process_Watcher
#define _Included_com_cayden_process_Watcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cayden_process_Watcher
 * Method:    createWatcher
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cayden_process_Watcher_createWatcher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cayden_process_Watcher
 * Method:    connectToMonitor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_cayden_process_Watcher_connectToMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_cayden_process_Watcher
 * Method:    sendMsgToMonitor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cayden_process_Watcher_sendMsgToMonitor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cayden_process_Watcher
 * Method:    getTestStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cayden_process_Watcher_getTestStr
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
